/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package warhorn.example;

import org.mockito.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  static final String SLUG = "deadbeef";
  static final String TOKEN = "foobar";

  @Test
  void appGetsAnEvent() {
    String expected = "mock value";

    GraphQLWebClient client = Mockito.mock(GraphQLWebClient.class);
    Mockito.when(client.post(ArgumentMatchers.any())).thenReturn(expected);

    App app = new App(client);
    String actual = app.getEvent(SLUG);

    assertEquals(expected, actual);
  }
}
